version: "3"
services:
  ######################################
  # Database Container
  ######################################
  database:
    container_name: parking-control-db
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "1234"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "parking-control-db"
    volumes:
      - postgres-data:/var/lib/postgresql/data

networks:
  app_net:
    driver: bridge
volumes:
  postgres-data:

